CompileFlags:
    Add:
        # Requires new clangd. I had good luck installing from GitHub releases into ~/.local/
        - --driver-mode=g++
    Remove:
        # - -march=*
        # - -mabi=*
        # - -mcpu=*
        - -mthumb-interwork

# Run all clang-tidy checks, except for https://github.com/clangd/clangd/issues/2665
Diagnostics:
    ClangTidy:
        FastCheckFilter: None
